name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy to gh pages
        run: npx angular-cli-ghpages --dir=dist/ms-web-client --no-silent
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
